module.exports = {
  ROOT_ATTR_VERSION: 0x01,


	ITEM_ATTR_FIRST: 0x10,
	ITEM_ATTR_SERVERID: 0x10,
	ITEM_ATTR_CLIENTID: 0x11,
	ITEM_ATTR_NAME: 0x12,
	ITEM_ATTR_DESCR: 0x13,
	ITEM_ATTR_SPEED: 0x14,
	ITEM_ATTR_SLOT: 0x15,
	ITEM_ATTR_MAXITEMS: 0x16,
	ITEM_ATTR_WEIGHT: 0x17,
	ITEM_ATTR_WEAPON: 0x18,
	ITEM_ATTR_AMU: 0x19,
	ITEM_ATTR_ARMOR: 0x1a,
	ITEM_ATTR_MAGLEVEL: 0x1b,
	ITEM_ATTR_MAGFIELDTYPE: 0x1c,
	ITEM_ATTR_WRITEABLE: 0x1d,
	ITEM_ATTR_ROTATETO: 0x1e,
	ITEM_ATTR_DECAY: 0x1f,
	ITEM_ATTR_SPRITEHASH: 0x20,
	ITEM_ATTR_MINIMAPCOLOR: 0x21,
	ITEM_ATTR_07: 0x22,
	ITEM_ATTR_08: 0x23,
	ITEM_ATTR_LIGHT: 0x24,

	//1-byte aligned
	ITEM_ATTR_DECAY2: 0x25, //deprecated
	ITEM_ATTR_WEAPON2: 0x26, //deprecated
	ITEM_ATTR_AMU2: 0x27, //deprecated
	ITEM_ATTR_ARMOR2: 0x28, //deprecated
	ITEM_ATTR_WRITEABLE2: 0x29, //deprecated
	ITEM_ATTR_LIGHT2: 0x2a,
	ITEM_ATTR_TOPORDER: 0x2b,
	ITEM_ATTR_WRITEABLE3: 0x2c, //deprecated

	ITEM_ATTR_WAREID: 0x2d,

  ITEM_ATTR_LAST: 0x2e,


	ITEM_GROUP_NONE: 0x00,

	ITEM_GROUP_GROUND: 0x01,
	ITEM_GROUP_CONTAINER: 0x02,
	ITEM_GROUP_WEAPON: 0x03, //deprecated
	ITEM_GROUP_AMMUNITION: 0x04, //deprecated
	ITEM_GROUP_ARMOR: 0x05, //deprecated
	ITEM_GROUP_CHARGES: 0x06,
	ITEM_GROUP_TELEPORT: 0x07, //deprecated
	ITEM_GROUP_MAGICFIELD: 0x08, //deprecated
	ITEM_GROUP_WRITEABLE: 0x09, //deprecated
	ITEM_GROUP_KEY: 0x0a, //deprecated
	ITEM_GROUP_SPLASH: 0x0b,
	ITEM_GROUP_FLUID: 0x0c,
	ITEM_GROUP_DOOR: 0x0d, //deprecated
	ITEM_GROUP_DEPRECATED: 0x0e,

  	ITEM_GROUP_LAST: 0x0f,


	FLAG_BLOCK_SOLID: 1 << 0,
	FLAG_BLOCK_PROJECTILE: 1 << 1,
	FLAG_BLOCK_PATHFIND: 1 << 2,
	FLAG_HAS_HEIGHT: 1 << 3,
	FLAG_USEABLE: 1 << 4,
	FLAG_PICKUPABLE: 1 << 5,
	FLAG_MOVEABLE: 1 << 6,
	FLAG_STACKABLE: 1 << 7,
	FLAG_FLOORCHANGEDOWN: 1 << 8, // unused
	FLAG_FLOORCHANGENORTH: 1 << 9, // unused
	FLAG_FLOORCHANGEEAST: 1 << 10, // unused
	FLAG_FLOORCHANGESOUTH: 1 << 11, // unused
	FLAG_FLOORCHANGEWEST: 1 << 12, // unused
	FLAG_ALWAYSONTOP: 1 << 13,
	FLAG_READABLE: 1 << 14,
	FLAG_ROTATABLE: 1 << 15,
	FLAG_HANGABLE: 1 << 16,
	FLAG_VERTICAL: 1 << 17,
	FLAG_HORIZONTAL: 1 << 18,
	FLAG_CANNOTDECAY: 1 << 19, // unused
	FLAG_ALLOWDISTREAD: 1 << 20,
	FLAG_UNUSED: 1 << 21, // unused
	FLAG_CLIENTCHARGES: 1 << 22, /* deprecated */
	FLAG_LOOKTHROUGH: 1 << 23,
	FLAG_ANIMATION: 1 << 24,
	FLAG_FULLTILE: 1 << 25, // unused
  FLAG_FORCEUSE: 1 << 26,


	ITEM_TYPE_NONE: 0x00,
	ITEM_TYPE_DEPOT: 0x01,
	ITEM_TYPE_MAILBOX: 0x02,
	ITEM_TYPE_TRASHHOLDER: 0x03,
	ITEM_TYPE_CONTAINER: 0x04,
	ITEM_TYPE_DOOR: 0x05,
	ITEM_TYPE_MAGICFIELD: 0x06,
	ITEM_TYPE_TELEPORT: 0x07,
	ITEM_TYPE_BED: 0x08,
	ITEM_TYPE_KEY: 0x09,
	ITEM_TYPE_RUNE: 0x0a,
	ITEM_TYPE_LAST: 0x0b
}
